# Generated by Django 3.0 on 2019-12-19 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universe',
            name='id',
        ),
        migrations.AddField(
            model_name='universe',
            name='universe_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universe',
            name='genre',
            field=models.CharField(choices=[('sf', 'space'), ('fa', 'fantasy'), ('pa', 'post-apocalyptic')], default='fa', max_length=20),
        ),
    ]
