# Generated by Django 3.0 on 2019-12-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0003_place_placedemographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='last_visited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
